[package]
name = "di_lay"
version = "0.1.0"
authors = ["stubiklaus <tobias-heinrichs@t-online.de>"]

[dependencies.vst2]
git = "https://github.com/overdrivenpotato/rust-vst2"

[lib]
name = "di_lay"
crate-type = ["dylib"]
